[project]
name = "prompt-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymupdf>=1.24.14",
    "pymupdf4llm>=0.0.17",
    "typer>=0.13.1",
]
